### ISSUE TITLE
Support exotic notations for Numbers

### ISSUE THREAD

**Issue by bartveneman** [omgovich/colord#39]
I know these are very unlikely patterns to run into, but apparently they exist, so support for them would be nice (but definitely not required):

```css
    numbers {
      color: rgba(1e2, .5e1, .5e0, +.25e2%);
    }
```
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_transparency_variations
