### ISSUE TITLE
Support exotic notations for angles in HSL

### ISSUE THREAD

**Issue by bartveneman** [omgovich/colord#40]
I know these are very unlikely patterns to run into, but apparently they exist, so support for them would be nice (but definitely not required):

```css
test-angles {
  color: hsl(.75turn, 60%, 70%);
  color: hsl(4.71239rad, 60%, 70%);
}
```

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsl_syntax_variations
